name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      postgres:
        image: postgres
        # refer: https://hub.docker.com/_/postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 25432:5432
    steps:
      - uses: actions/checkout@v5
      - uses: ariga/setup-atlas@master
      - uses: actions/setup-node@v6
        with:
          cache: "npm"
      - run: npm install
      - run: npm run lint
      - run: npm test run
