name: Test Track.js

on:
  pull_request:
    branches:
      # https://github.com/peter-evans/create-pull-request/tree/v6/#:~:text=request%20branch%20name.-,create%2Dpull%2Drequest/patch,-delete%2Dbranch
      - create-pull-request/patch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm install
      - run: npm test run src/const/track.test.js
