name: Test Track.js

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    # https://github.com/peter-evans/create-pull-request/tree/v6/#:~:text=request%20branch%20name.-,create%2Dpull%2Drequest/patch,-delete%2Dbranch
    if: ${{ github.head_ref == 'create-pull-request/patch' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm install
      - run: npm test run src/const/track.test.js
