name: Test

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        # refer: https://hub.docker.com/_/postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        ports:
          - 25432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ariga/setup-atlas@master
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm install
      - run: npm test run
